exclude: [docs, node_modules, pictures, prepared, CONTRIBUTING.md, gulpfile.js, index.html, LICENSE.md, netlify.toml, package-lock.json, package.json, README.md]

collections:
  slides:
    output: false
