backend:
  name: git-gateway
  branch: cms # Branch to update (optional; defaults to master)

media_folder: "pictures"

collections:
  - name: "slides" # Used in routes, e.g., /admin/collections/blog
    label: "Slides" # Used in the UI
    folder: "_slides/"
    create: true
    slug: "{{day}}{{hour}}{{minute}}{{second}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Slide Number"
        name: "number"
        widget: "number"
        default: 0
        valueType: "int"
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
  - name: "settings"
    label: "Settings"
    files:
      - label: "Global"
        name: "global"
        file: "_data/global.yml"
        fields:
        - label: Language
          name: lang
          widget: select
          options: ["en", "ru"]
          required: false
        - label: Caption title
          name: title
          widget: string
          required: false
        - label: Caption subtitle
          name: subtitle
          widget: string
          required: false
        - {label: Mode, name: mode, widget: select, options: ["list", "full"]}
        - {label: Progress Bar, name: progress, widget: boolean}
        - label: "Badge"
          name: badge
          widget: "object"
          fields:
            - {label: "Show badge", name: badge-show, widget: boolean}
            - label: "Badge text"
              name: "badge-text"
              widget: "string"
              required: false
            - label: "Badge link"
              name: "badge-link"
              widget: "string"
              required: false

